//------------------------------------------------------------------------------
//
// Design unit generated by Aldec IP Core Generator, version 9.1.
// Copyright (c) 1997 - 2011 by Aldec, Inc. All rights reserved.
//
//------------------------------------------------------------------------------
//
// Created on Tuesday 2013-10-29, 11:40:43
//
//------------------------------------------------------------------------------
// Details:
//		Type: Asynchronous dual port Random Access Memory (RAM)
//		Word size: 8 bits
//		Memory depth: 256 words
//		Write enable input WE active high
//------------------------------------------------------------------------------

//{{ Section below this comment is automatically maintained
//   and may be overwritten
//{module {ram}}

module mem1_8x8(WE, DATA, Q, ADDRrd, ADDRwr);

output [7:0] Q;
input [7:0] DATA;
input [7:0] ADDRrd;
input [7:0] ADDRwr;
input WE;

//}} End of automatically maintained section

reg [7:0] ram_MEM [255:0];

	always @(WE or ADDRwr or DATA)
	begin
		if (WE == 1'b1)
			ram_MEM[ADDRwr] <= DATA;
	end

	assign Q= ram_MEM[ADDRrd];

endmodule

