//------------------------------------------------------------------------------
//
// Design unit generated by Aldec IP Core Generator, version 9.1.
// Copyright (c) 1997 - 2011 by Aldec, Inc. All rights reserved.
//
//------------------------------------------------------------------------------
//
// Created on Monday 2013-11-11, 12:44:58
//
//------------------------------------------------------------------------------
// Details:
//		Type: Synchronous dual port Random Access Memory (RAM)
//		Word size: 8 bits
//		Memory depth: 256 words
//		Clock input CLK active high
//		Write enable input WE active high
//------------------------------------------------------------------------------

//{{ Section below this comment is automatically maintained
//   and may be overwritten
//{module {ram8x8_clk}}

module ram8x8_clk(WE, CLK, DATA, Q, ADDRrd, ADDRwr);

output [7:0] Q;
input [7:0] DATA;
input [7:0] ADDRrd;
input [7:0] ADDRwr;
input WE;
input CLK;

//}} End of automatically maintained section

reg [7:0] ram8x8_clk_MEM [255:0];

	always @(posedge CLK)
	begin
		if (WE == 1'b1)
			ram8x8_clk_MEM[ADDRwr] <= DATA;
	end

	assign Q= ram8x8_clk_MEM[ADDRrd];

endmodule

