////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 14.4
//  \   \         Application : xaw2verilog
//  /   /         Filename : dcm_main1.v
// /___/   /\     Timestamp : 09/11/2013 12:12:54
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -st C:/Xilinx_project/B610_sinhron/ipcore_dir/dcm_main1.xaw C:/Xilinx_project/B610_sinhron/ipcore_dir/dcm_main1
//Design Name: dcm_main1
//Device: xc3s500e-5pq208
//
// Module dcm_main1
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// Period Jitter (unit interval) for block DCM_SP_INST2 = 0.05 UI
// Period Jitter (Peak-to-Peak) for block DCM_SP_INST2 = 0.78 ns
`timescale 1ns / 1ps

module dcm_main1(U1_CLKIN_IN, 
                 U1_RST_IN, 
                 U1_U2_SELECT_IN, 
                 U2_CLKIN_IN, 
                 U2_RST_IN, 
                 CLKFX_OUT, 
                 U1_CLKIN_IBUFG_OUT, 
                 U1_CLK0_OUT, 
                 U1_LOCKED_OUT, 
                 U1_U2_CLK_OUT, 
                 U2_CLKIN_IBUFG_OUT, 
                 U2_LOCKED_OUT);

    input U1_CLKIN_IN;
    input U1_RST_IN;
    input U1_U2_SELECT_IN;
    input U2_CLKIN_IN;
    input U2_RST_IN;
   output CLKFX_OUT;
   output U1_CLKIN_IBUFG_OUT;
   output U1_CLK0_OUT;
   output U1_LOCKED_OUT;
   output U1_U2_CLK_OUT;
   output U2_CLKIN_IBUFG_OUT;
   output U2_LOCKED_OUT;
   
   wire GND_BIT;
   wire U1_CLKFB_IN;
   wire U1_CLKIN_IBUFG;
   wire U1_CLK0_BUF;
   wire U2_CLKFX_BUF;
   wire U2_CLKIN_IBUFG;
   
   assign GND_BIT = 0;
   assign U1_CLKIN_IBUFG_OUT = U1_CLKIN_IBUFG;
   assign U1_CLK0_OUT = U1_CLKFB_IN;
   assign U2_CLKIN_IBUFG_OUT = U2_CLKIN_IBUFG;
   BUFGMUX  BUFGMUX_INST (.I0(U1_CLK0_BUF), 
                         .I1(U2_CLKFX_BUF), 
                         .S(U1_U2_SELECT_IN), 
                         .O(U1_U2_CLK_OUT));
   DCM_SP #( .CLK_FEEDBACK("1X"), .CLKDV_DIVIDE(2.0), .CLKFX_DIVIDE(1), 
         .CLKFX_MULTIPLY(4), .CLKIN_DIVIDE_BY_2("FALSE"), 
         .CLKIN_PERIOD(15.625), .CLKOUT_PHASE_SHIFT("NONE"), 
         .DESKEW_ADJUST("SYSTEM_SYNCHRONOUS"), .DFS_FREQUENCY_MODE("LOW"), 
         .DLL_FREQUENCY_MODE("LOW"), .DUTY_CYCLE_CORRECTION("TRUE"), 
         .FACTORY_JF(16'hC080), .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE") ) 
         DCM_SP_INST1 (.CLKFB(U1_CLKFB_IN), 
                        .CLKIN(U1_CLKIN_IBUFG), 
                        .DSSEN(GND_BIT), 
                        .PSCLK(GND_BIT), 
                        .PSEN(GND_BIT), 
                        .PSINCDEC(GND_BIT), 
                        .RST(U1_RST_IN), 
                        .CLKDV(), 
                        .CLKFX(), 
                        .CLKFX180(), 
                        .CLK0(U1_CLK0_BUF), 
                        .CLK2X(), 
                        .CLK2X180(), 
                        .CLK90(), 
                        .CLK180(), 
                        .CLK270(), 
                        .LOCKED(U1_LOCKED_OUT), 
                        .PSDONE(), 
                        .STATUS());
   DCM_SP #( .CLK_FEEDBACK("NONE"), .CLKDV_DIVIDE(2.0), .CLKFX_DIVIDE(1), 
         .CLKFX_MULTIPLY(3), .CLKIN_DIVIDE_BY_2("FALSE"), 
         .CLKIN_PERIOD(50.000), .CLKOUT_PHASE_SHIFT("NONE"), 
         .DESKEW_ADJUST("SYSTEM_SYNCHRONOUS"), .DFS_FREQUENCY_MODE("LOW"), 
         .DLL_FREQUENCY_MODE("LOW"), .DUTY_CYCLE_CORRECTION("TRUE"), 
         .FACTORY_JF(16'hC080), .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE") ) 
         DCM_SP_INST2 (.CLKFB(GND_BIT), 
                        .CLKIN(U2_CLKIN_IBUFG), 
                        .DSSEN(GND_BIT), 
                        .PSCLK(GND_BIT), 
                        .PSEN(GND_BIT), 
                        .PSINCDEC(GND_BIT), 
                        .RST(U2_RST_IN), 
                        .CLKDV(), 
                        .CLKFX(U2_CLKFX_BUF), 
                        .CLKFX180(), 
                        .CLK0(), 
                        .CLK2X(), 
                        .CLK2X180(), 
                        .CLK90(), 
                        .CLK180(), 
                        .CLK270(), 
                        .LOCKED(U2_LOCKED_OUT), 
                        .PSDONE(), 
                        .STATUS());
   IBUFG  U1_CLKIN_IBUFG_INST (.I(U1_CLKIN_IN), 
                              .O(U1_CLKIN_IBUFG));
   BUFG  U1_CLK0_BUFG_INST (.I(U1_CLK0_BUF), 
                           .O(U1_CLKFB_IN));
   BUFG  U2_CLKFX_BUFG_INST (.I(U2_CLKFX_BUF), 
                            .O(CLKFX_OUT));
   IBUFG  U2_CLKIN_IBUFG_INST (.I(U2_CLKIN_IN), 
                              .O(U2_CLKIN_IBUFG));
endmodule
