////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 14.4
//  \   \         Application : xaw2verilog
//  /   /         Filename : dcm2.v
// /___/   /\     Timestamp : 06/26/2015 17:53:17
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -intstyle C:/SOFT_project/FPGA/Xilinx_project/Sinhron_B600/B700_sinhron_V4/ipcore_dir/dcm2.xaw -st dcm2.v
//Design Name: dcm2
//Device: xc3s500e-5pq208
//
// Module dcm2
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// Period Jitter (unit interval) for block DCM_SP_INST = 0.04 UI
// Period Jitter (Peak-to-Peak) for block DCM_SP_INST = 1.87 ns
`timescale 1ns / 1ps

module dcm2(CLKIN_IN, 
            RST_IN, 
            CLKDV_OUT, 
            CLKFX_OUT, 
            CLK0_OUT);

    input CLKIN_IN;
    input RST_IN;
   output CLKDV_OUT;
   output CLKFX_OUT;
   output CLK0_OUT;
   
   wire CLKFB_IN;
   wire CLK0_BUF;
   wire GND_BIT;
   
   assign GND_BIT = 0;
   assign CLK0_OUT = CLKFB_IN;
   BUFG  CLK0_BUFG_INST (.I(CLK0_BUF), 
                        .O(CLKFB_IN));
   DCM_SP #( .CLK_FEEDBACK("1X"), .CLKDV_DIVIDE(3.5), .CLKFX_DIVIDE(16), 
         .CLKFX_MULTIPLY(5), .CLKIN_DIVIDE_BY_2("FALSE"), 
         .CLKIN_PERIOD(15.625), .CLKOUT_PHASE_SHIFT("NONE"), 
         .DESKEW_ADJUST("SOURCE_SYNCHRONOUS"), .DFS_FREQUENCY_MODE("LOW"), 
         .DLL_FREQUENCY_MODE("LOW"), .DUTY_CYCLE_CORRECTION("TRUE"), 
         .FACTORY_JF(16'hC080), .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE") ) 
         DCM_SP_INST (.CLKFB(CLKFB_IN), 
                       .CLKIN(CLKIN_IN), 
                       .DSSEN(GND_BIT), 
                       .PSCLK(GND_BIT), 
                       .PSEN(GND_BIT), 
                       .PSINCDEC(GND_BIT), 
                       .RST(RST_IN), 
                       .CLKDV(CLKDV_OUT), 
                       .CLKFX(CLKFX_OUT), 
                       .CLKFX180(), 
                       .CLK0(CLK0_BUF), 
                       .CLK2X(), 
                       .CLK2X180(), 
                       .CLK90(), 
                       .CLK180(), 
                       .CLK270(), 
                       .LOCKED(), 
                       .PSDONE(), 
                       .STATUS());
endmodule
