//----------------------------------------------------------------------------------
//
// Design unit generated by Aldec IP Core Generator, version 7.2.
// Copyright (c) 2003-2006 by Aldec, Inc. All rights reserved.
//
//----------------------------------------------------------------------------------
//
// Created on Tuesday 2012-05-22, 17:12:31
//
//----------------------------------------------------------------------------------
// Details:
//		Type: Synchronous dual port Random Access Memory (RAM)
//		Word size: 16 bits
//		Memory depth: 256 words
//		Clock input CLK active high
//		Write enable input WE active high
//----------------------------------------------------------------------------------

//{{ Section below this comment is automatically maintained
//   and may be overwritten
//{module {ram16x256_v1}}

module ram16x256_v1(WE, CLK, DATA, Q, ADDRrd, ADDRwr);

output [15:0] Q;
input [15:0] DATA;
input [7:0] ADDRrd;
input [7:0] ADDRwr;
input WE;
input CLK;

//}} End of automatically maintained section

reg [15:0] ram16x256_v1_MEM [255:0];

	always @(posedge CLK)
	begin
		if (WE == 1'b1)
			ram16x256_v1_MEM[ADDRwr] <= DATA;
	end

	assign Q= ram16x256_v1_MEM[ADDRrd];

endmodule

