//------------------------------------------------------------------------------
//
// Design unit generated by Aldec IP Core Generator, version 9.1.
// Copyright (c) 1997 - 2011 by Aldec, Inc. All rights reserved.
//
//------------------------------------------------------------------------------
//
// Created on Wednesday 2013-11-06, 16:54:12
//
//------------------------------------------------------------------------------
// Details:
//		Type: Synchronous dual port Random Access Memory (RAM)
//		Architecture dedicated for Xilinx devices
//		Word size: 32 bits
//		Memory depth: 16 words
//		Clock input CLK active high
//		Write enable input WE active high
//------------------------------------------------------------------------------

//{{ Section below this comment is automatically maintained
//   and may be overwritten
//{module {ram32x16_v2}}

module ram32x16 (WE, CLK, DATA, Q, ADDRrd, ADDRwr);

output [31:0] Q;

input [31:0] DATA;
input [3:0] ADDRrd;
input [3:0] ADDRwr;
input WE;
input CLK;

//}} End of automatically maintained section

	RAM16X1D U16_0 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[0]), .DPO(Q[0]), .SPO());
	RAM16X1D U16_1 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[1]), .DPO(Q[1]), .SPO());
	RAM16X1D U16_2 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[2]), .DPO(Q[2]), .SPO());
	RAM16X1D U16_3 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[3]), .DPO(Q[3]), .SPO());
	RAM16X1D U16_4 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[4]), .DPO(Q[4]), .SPO());
	RAM16X1D U16_5 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[5]), .DPO(Q[5]), .SPO());
	RAM16X1D U16_6 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[6]), .DPO(Q[6]), .SPO());
	RAM16X1D U16_7 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[7]), .DPO(Q[7]), .SPO());
	RAM16X1D U16_8 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[8]), .DPO(Q[8]), .SPO());
	RAM16X1D U16_9 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[9]), .DPO(Q[9]), .SPO());
	RAM16X1D U16_10 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[10]), .DPO(Q[10]), .SPO());
	RAM16X1D U16_11 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[11]), .DPO(Q[11]), .SPO());
	RAM16X1D U16_12 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[12]), .DPO(Q[12]), .SPO());
	RAM16X1D U16_13 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[13]), .DPO(Q[13]), .SPO());
	RAM16X1D U16_14 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[14]), .DPO(Q[14]), .SPO());
	RAM16X1D U16_15 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[15]), .DPO(Q[15]), .SPO());
	RAM16X1D U16_16 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[16]), .DPO(Q[16]), .SPO());
	RAM16X1D U16_17 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[17]), .DPO(Q[17]), .SPO());
	RAM16X1D U16_18 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[18]), .DPO(Q[18]), .SPO());
	RAM16X1D U16_19 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[19]), .DPO(Q[19]), .SPO());
	RAM16X1D U16_20 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[20]), .DPO(Q[20]), .SPO());
	RAM16X1D U16_21 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[21]), .DPO(Q[21]), .SPO());
	RAM16X1D U16_22 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[22]), .DPO(Q[22]), .SPO());
	RAM16X1D U16_23 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[23]), .DPO(Q[23]), .SPO());
	RAM16X1D U16_24 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[24]), .DPO(Q[24]), .SPO());
	RAM16X1D U16_25 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[25]), .DPO(Q[25]), .SPO());
	RAM16X1D U16_26 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[26]), .DPO(Q[26]), .SPO());
	RAM16X1D U16_27 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[27]), .DPO(Q[27]), .SPO());
	RAM16X1D U16_28 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[28]), .DPO(Q[28]), .SPO());
	RAM16X1D U16_29 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[29]), .DPO(Q[29]), .SPO());
	RAM16X1D U16_30 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[30]), .DPO(Q[30]), .SPO());
	RAM16X1D U16_31 (.WE(WE), .WCLK(CLK), .A0(ADDRwr[0]), .A1(ADDRwr[1]), .A2(ADDRwr[2]), .A3(ADDRwr[3]), .DPRA0(ADDRrd[0]), .DPRA1(ADDRrd[1]), .DPRA2(ADDRrd[2]), .DPRA3(ADDRrd[3]), .D(DATA[31]), .DPO(Q[31]), .SPO());


endmodule
